apiVersion: v2
name: nginx
type: application

version: 0.0.0

dependencies:
- name: app
  version: "0.1.6"
  repository: https://kargotech.github.io/icarus
  alias: app
- name: app-network
  version: "0.1.2"
  repository: https://kargotech.github.io/icarus
